### ISSUE TITLE
Add instructions for configuring Linux server

### ISSUE THREAD

**Issue by laheadle** [GsDevKit/GsDevKit_home#1]
I realize this is already on your todo list but an explicit issue is nice for tracking purposes.

I may be able to do this myself as I am reading the SysAdmin guide. If I recall correctly, this is mostly setting up shared memory and file descriptor limits, disks, swap partitions, etc.

Not sure if there is any additional configuration on the server specific to GsDevKit_home

**Comment by dalehenrich** [comment]
thanks @laheadle ... the shared memory and file descriptors are set up automatically in the [$GS_HOME/bin/downloadGemStone](https://github.com/GsDevKit/GsDevKit_home/blob/master/bin/downloadGemStone#L158-L270) script... then the [$GS_HOME/bin/utils/installOSPrereqs](https://github.com/GsDevKit/GsDevKit_home/blob/master/bin/utils/installOsPrereqs) does have the os prereqs for Ubunutu 12.04 and 14.04 .... but I don't have setup information there for **disk swap** and I think that is a good point  that should be included !

My feeling is that if I have entries in the installOsPrereqs that works for a simple installation, then as users get more serious they will relaize that there are disk dials to be twirled ...

THX!

**Comment by dalehenrich** [comment]
With the recent set of changes for [Milestone 1.0.0](https://github.com/GsDevKit/GsDevKit_home/milestones/1.0.0), the installOsPrereqs script is run as part of the install ... so prereqs including shared memory setup is done as part of the install process
