### ISSUE TITLE
Use https://downloads.gemtalksystems.com in $GS_HOME/bin/downloadGemStone

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#120]
See #114 for a bit more context ... ftp site has been updated (internal bug 46203 is fixed)

**Comment by jbrichau** [comment]
Would be cool to have it updated to reflect the changes to the script it $GS_HOME. I'm still using that script because we have our own install and dowloading this entire repo first to use the download script here seems a bit overkill.

**Comment by jbrichau** [comment]
Then again, `GemStone64Bit2.4.4.1-i386.Darwin` is missing from the ftp site. Will this be downloadable again? Unfortunately, we still need it (for now).

**Comment by dalehenrich** [comment]
This message isn't visible up on github ... di d you delete this message 
and the follow-on or is there something else afoot?

Dale

**Comment by jbrichau** [comment]
I deleted it because I noticed it has no relation to issue :)


Johan (sent from my mobile)
