### ISSUE TITLE
Add netldi magic line into autogenerated .topazini

### ISSUE THREAD

**Issue by marianopeck** [GsDevKit/GsDevKit_home#161]
In order to connect from topaz with RPC we need the netldi magic line in the .topazini. It would be nice if GsDevKit_home can add that in the auto-generated .topazini:

`startTopaz myStone_333 -r -I $GS_HOME/server/stones/lucidiaLLC_333/.topazini`

And  in `topaz.ini` add:

`set gemnetid !tcp@localhost#netldi:40600#task!gemnetobject`

**Comment by dalehenrich** [comment]
startTopaz already uses `-I` to pick up the .topazini, but yes, the gemnetid line needs to be added ... I'll look into that right now ... while the iron is hot:)

**Comment by dalehenrich** [comment]
@marianopeck here's a sample `.topazini`:

```
SET GEMSTONE test_333
set user DataCurator
set password swordfish
set gemnetid !tcp@foos#netldi:test_333_ldi#task!gemnetobject
```

Note that I'm using the name of the netldi: `test_333_ldi` not the port number. At the time the .topazini is generated a netldi port number is not known ... A port number is really only needed if you are using topaz for remote logins and you have nut associated the netldi name with a port number in `/etc/services` ... on the local host the netldi name is fine ...

What do you think?

**Comment by dalehenrich** [comment]
Tested things locally and they work ... also added a symlink from `$GS_HOME/server/stones/<stone-name>/tode` to `$GS_HOME/sys/local/server/stones/<stone-name>` ... more than once I've wanted to see what tODE scripts were available when sitting the  `$GS_HOME/server/stones` directory and vowed to add the link ... today I remembered my vow  ... hot irons and all that:)

**Comment by dalehenrich** [comment]
Sure enough there are some errors and failures when run in 3.3.3:

```
35 run, 32 passes, 0 expected defects, 1 failures, 2 errors, 0 unexpected passes
  35 tests
  35 run ['done']
  32 passes
  0 expected defects
  1 failures
UTF16TextConverterTest>>#testBOMWrite
  2 errors
GsPharoSplitTests>>#testJoinArrayUsingSortedCollection
UTF16TextConverterTest>>#testByteOrders
  0 unexpected passes
```

**Comment by dalehenrich** [comment]
oops that comment was aimed at [a bug in a completely different project](https://github.com/glassdb/PharoCompatibility/issues/7)

**Comment by marianopeck** [comment]
@dalehenrich  sure, using the netldi name rather than port is much better

**Comment by dalehenrich** [comment]
[builds are green](https://travis-ci.org/GsDevKit/GsDevKit_home/builds/195981491)

**Comment by dalehenrich** [comment]
There are issues with topaz running as rpc rather than linked with stdout going to the gem log instead of stdout, so we need to not include the gemnetid by default ... I think leaving it in and commenting it out is a good compromise

**Comment by marianopeck** [comment]
Yes, I agree it is a good compromise (workaround) until the topaz -l is honored even if that line is present.

**Comment by dalehenrich** [comment]
`set gemnetid` now commented out ...
