### ISSUE TITLE
Can we make tODE install backups optional? 

### ISSUE THREAD

**Issue by marianopeck** [GsDevKit/GsDevKit_home#164]
Hi @dalehenrich 

As you know, as part of the `upgradeStone` when it comes to load tODE it does backups. See this part of a log:

	Loaded -> Tode-Remote-Server-dkh.18 --- filetree://$GS_HOME/shared/repos/tode/repository [cdd9696:dev] --- cache
	Evaluated -> baseline [BaselineOfTode] >> initializeTools
	...finished baseline
	Bulk migrate of 0 candidate classes
	        No instance migrations performed.[01/30/2017 16:34:52.586 EST]
	  gci login: currSession 1  rpc gem processId 3728 socket 10

	---Starting backup to '$GS_HOME/server/stones/debrisDemo_333/backups//tode.dbf.gz' (01/30/2017 16:34:53)
	---validating backup (01/30/2017 17:03:28)
	'$GS_HOME/server/stones/debrisDemo_333/product/bin/copydbf  $GS_HOME/server/stones/debrisDemo_333/backups//tode.dbf.gz /dev/null'
	Source file: $GS_HOME/server/stones/debrisDemo_333/backups//tode.dbf.gz
	   File type: backup  fileId: 0 in a backup set with 1 files
	   ByteOrder: Intel (LSB first)  compatibilityLevel: 846
	   The file was created at: 01/30/2017 16:34:53 EST
	Destination file:  /dev/null
	   ByteOrder: Intel (LSB first)
	   Full backup started from checkpoint at: 01/30/2017 16:34:52 EST.
	   Oldest tranlog needed for restore is fileId 1710 ( tranlog1710.dbf ).
	   Backup was created by GemStone Version: 3.3.3.
	File contains 362030 records,  occupying 47452.0 MBytes

	---Finished backup to 30/01/2017 17:03:28 -- tode.dbf.gz
	---Starting snapshot to '$GS_HOME/server/stones/debrisDemo_333/extents/extent0.dbf $GS_HOME/server/stones/debrisDemo_333/snapshots///extent0.tode.dbf'(01/30/2017 17:06:33)
	        ---Finishing snapshot 01/30/2017 17:07:06 -- $GS_HOME/server/stones/debrisDemo_333/snapshots///extent0.tode.dbf
	a Text for '[32364694017 sz:1 Array] anArray( ''$GS_HOME/server/stones/debrisDemo_333/snapshots///extent0.tode.dbf'')'
	...finished :: todeLoad debrisDemo_333
	...finished :: todeLoad debrisDemo_333
	Performing post upgrade tasks

	Post Upgrade Script:
	        /home/utils/upgrade/postUpgrade --sourceVersion=3.2.9
	[Info]: libssl-3.3.3-32.so: loaded
	[01/30/2017 17:07:08.442 EST]
	  gci login: currSession 1  rpc gem processId 5250 socket 10

Now, I would like to make those backups optional. Why? Well, first because most of the times I run out of hard disk space (even if backups are compressed), but in addition, because I AM CREATING A NEW STONE while doing `upgradeStone` ... so.. I don't need backups for installing tODE (which I see it just as another step of the upgrade... so if something went wrong, then I can start fresh with `upgradeStone`. In fact, I may hit an issue while installing tODE and even with the backup...I wouldn't bet the state of the `upgradeStone`. Too risky to try to resume from the tode backup.

I understand that when you simply want to load tODE then it makes sense to auto-generate backups...but for when using it from `upgradeStone` it may not make sense. 

again, I know I can override load tODE script locally, but that's not the case because that's general. I am spotting the concrete scenario when using `upgradeStone`.

**Comment by marianopeck** [comment]
OK...I think I never like the `tODE` autobackups...even if I would like to install tODE from scratch. I think backups should be done explicitly by the user, whenever he is about to install something risky. So...could you tell me if the following is correct? Create this file: `/home/quuve/GsDevKit_home/sys/default/client/tode-scripts/loadServerTode2` like this



	[quuve@quuveserver1 tode-scripts]$ vim loadServerTode2
	script --script=setUpSys      # set up the in-image tODE /sys structure

**Comment by dalehenrich** [comment]
You change to `loadServerTode2` is correct. Look at the [scripts that are modified for running tests on travis](https://github.com/GsDevKit/GsDevKit_home/tree/master/tests/sys/local/client/tode-scripts) for two more scripts that you should modify. `rebuildServerTode` and `updateServerTode` both do backups as well ... backups randomly fail when done on travis so I removed the backups but left the snapshots ... you probably don't want snapshots either ...

**Comment by dalehenrich** [comment]
I kind of figure that you either want backups in these *standard spots* or you don't want them at all.

**Comment by marianopeck** [comment]
OK, thanks @dalehenrich 

Yes, I think I came to the same conclusion. So I close this issue.
