### ISSUE TITLE
Error: while installing tODE on server. MCClassDefinition does not understand ...

### ISSUE THREAD

**Issue by KobusErasmus** [GsDevKit/GsDevKit_home#170]
While following the install seaside instructions (found here: https://github.com/GsDevKit/GsDevKit_seaside31/blob/master/docs/installation/installSeasideServer.md), the following error occurs:

> Error: while installing tODE on server: 'a MessageNotUnderstood occurred (error 2010), a MCClassDefinition does not understand  #''initializeWithName:superclassName:traitComposition:classTraitComposition:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp:'''

A snippet from the stack:

> Loaded -> Monticello.v3-dkh.487 --- filetree:///home/.../projects/GsDevKit_home/shared/repos/glass/repository [f48e79f:master] --- cache
> ========>Server Stack: 'a MessageNotUnderstood occurred (error 2010), a MCClassDefinition does not understand  #''initializeWithName:superclassName:traitComposition:classTraitComposition:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp:'''
> 
> 1 [] in  ExecBlock1 (GsUpgrader class) >> batchErrorHandlingDo: @12 line 9  [GsNMethod 107926273]
> 
> 2 MessageNotUnderstood (AbstractException) >> _executeHandler: @4 line 8  [GsNMethod 4042753]
> 
> 3 MessageNotUnderstood (AbstractException) >> _signalWith: @1 line 1  [GsNMethod 4171265]
> 
> 4 MessageNotUnderstood (AbstractException) >> signal @2 line 47  [GsNMethod 4206849]
> 
> 5 MCClassDefinition (Object) >> doesNotUnderstand: @10 line 10  [GsNMethod 3532289]
> 
> 6 MCClassDefinition (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12  [GsNMethod 3529473]
> 7 MCClassDefinition class >> name:superclassName:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp: @3 line 12  [GsNMethod 151336705]
> 
> 8 Issue285Test class (Class) >> asClassDefinition @15 line 3  [GsNMethod 43337473]
> 
> 9 Issue285Test class (Class) >> classDefinitions @2 line 2  [GsNMethod 43351809]
> 
> 10 [] in  ExecBlock1 (MCPackage) >> snapshot @39 line 20  [GsNMethod 151892481]
> 
> 11 IdentitySet (IdentityBag) >> do: @7 line 8  [GsNMethod 3736065]
> 
> 12 PackageInfo >> coreMethods:extensionMethods:overriddenMethods:classes: @11 line 48  [GsNMethod 151678465]
> 
> 13 MCPackage >> snapshot @18 line 14  [GsNMethod 151679489]
> 
> 14 MCPackageLoader >> updatePackage:withSnapshot: @3 line 3  [GsNMethod 34875393]
> 
> 15 [] in  ExecBlock1 (MCVersionLoader) >> load @19 line 5  [GsNMethod 39960321]
> 
> 16 OrderedCollection (Collection) >> do: @6 line 10  [GsNMethod 2446849]
> 
> 17 MCVersionLoader >> load @6 line 5  [GsNMethod 34359553]
> 
> 18 MetacelloGoferLoad (GoferLoad) >> execute @6 line 3  [GsNMethod 34545153]
> 
> 19 [] in  ExecBlock0 (MetacelloCommonMCSpecLoader) >> loadPackageDirective:gofer: @47 line 17  [GsNMethod 121703937]
> 
> 20 [] in  ExecBlock0 (MetacelloCommonMCSpecLoader) >> loadPackageDirective:gofer: @24 line 21  [GsNMethod 120899329]

**Comment by dalehenrich** [comment]
@KobusErasmus I think I need to see a bit more of the log files to understand what may be going wrong here. 

I am inclined to recommend [installing Seaside into a an existing GsDevKit_home stone](https://github.com/GsDevKit/GsDevKit_home/blob/master/docs/gettingStartedWithSeaside.md) as the standard stone creation code is exercised more often by Travis... However, I don't think that you've gotten that far yet to where it might make a difference ..

Typically there is a list of bash shell script calls dumped to `stdout` and highlighted red, when an error occurs, and to start, I'd like to see that so that I can get my bearings as to which part of the stone creation process you are in ... then I'd like to see a bit more of the Metacello log leading up to the error...

**Comment by dalehenrich** [comment]
Oh. I'd also like to know which os platform you are running on ...

**Comment by KobusErasmus** [comment]
Thanks @dalehenrich. I am not in the office today, but tomorrow I will try send you those log files. I tried installing it on Ubuntu 16.04. Yes, installing Seaside into an existing stone sounds like a better option, and I will give that a try as well.

**Comment by KobusErasmus** [comment]
I have tried to re-create the error on my Ubuntu 16.10 PC at home. But I get an "unrecognized Ubuntu version"? I ran:

> $ installServerSeaside -c https -z 8383 seaside_333 3.3.3

And the output:

>    GsDevKit script: installServerSeaside -c https -z 8383 seaside_333 3.3.3
>               path: /home/vaugnx1/GsDevKit/GsDevKit_home/etc/GsDevKit_seaside31/bin/installServerSeaside
>
>
>    GsDevKit script: setupGsDevKit -c https server
>               path: /home/vaugnx1/GsDevKit/GsDevKit_home/bin/setupGsDevKit
> 
>    GsDevKit script: installOsPrereqs server
>               path: /home/vaugnx1/GsDevKit/GsDevKit_home/bin/utils/installOsPrereqs
>
> [sudo] password for vaugnx1: 
> Tue Mar 21 08:43:04 SAST 2017
> [Info] Setting up shared memory
>   Total memory available is 7856 MB
>   Max shared memory segment size is -16 MB
>   Max shared memory allowed is -65536 MB
> /home/vaugnx1/GsDevKit/GsDevKit_home/bin/utils/installOsPrereqs: line 240: [: 18446744073692774399: integer expression expected
> /home/vaugnx1/GsDevKit/GsDevKit_home/bin/utils/installOsPrereqs: line 244: [: 18446744073692774399: integer expression expected
> [Info] No need to increase max shared memory segment size
> /home/vaugnx1/GsDevKit/GsDevKit_home/bin/utils/installOsPrereqs: line 256: [: 18446744073692774399: integer expression expected
> [Info] No need to increase max shared memory allowed
> [Info] Setting up GemStone netldi service port
> [Info] Adding "gs64ldi  50377/tcp" to /etc/services
> [Info] Creating /opt/gemstone directory
> Tue Mar 21 08:43:04 SAST 2017
> Installing prereqs for detect Linux named Ubuntu and version 16.10
>   USAGE: installOsPrereqs [-h] client|server|both
> 
>   Verify machine is capable of running GemStone 64-bit (Mac and Linux)
>   Add shared memory setup to /etc/sysctl.conf (Mac and Linux)
>   Add GemStone netldi service port to /etc/services (Mac and Linux)
>   Install operating system prerequisites (Ubuntu14.04 and Ubuntu12.04)
> 
>   Should not be run as root `sudo` is used to install operating system prereqs and
>   setup shared memory (Mac and Linux)EXAMPLES
>    installOsPrereqs -h
>    installOsPrereqs client
>    installOsPrereqs server
>    installOsPrereqs both
> 
> unrecognized Ubuntu version  :: installOsPrereqs server
> Error on or near line 58 :: setupGsDevKit -c https server :: setupGsDevKit -c https server

**Comment by dalehenrich** [comment]
Ah, you are running on 16.10 and the [installOSPrereqs script is wired for 16.04](https://github.com/GsDevKit/GsDevKit_home/commit/62666224ca32c96d8dfadb85e1ddd30f2a3f10d8) ... I suppose that change should be `16.*` instead of `16.04` --- could you verify?

**Comment by KobusErasmus** [comment]
Yes, when I change "16.04" to "16.*" in the installOSPrereqs script, the script runs. This solves the installation on 16.10 issue, but I still faced the initial MessageNotUnderstood problem. After looking through the logs I noticed that many git files could not be checked out because their file name is too long. For example:

> Cloning into 'tode'...
> remote: Counting objects: 89074, done.
> remote: Total 89074 (delta 0), reused 0 (delta 0), pack-reused 89073
> Receiving objects: 100% (89074/89074), 25.76 MiB | 177.00 KiB/s, done.
> Resolving deltas: 100% (38822/38822), done.
> Checking connectivity... done.
> ...finished :: cloneGitHubProject -n -c https dalehenrich tode
>
>    Checkout tode
>
> error: unable to create file repository/Topez-Server-Core.package/TDMetacelloTool.class/instance/projectNew.projectEntryPath.packageName.gitRootPath.requiredProjects.dependencies.repositories.superclassName.applicationClassCreationBlock.force..st: File name too long
> D	repository/Topez-Server-Core.package/TDMetacelloTool.class/instance/projectNew.projectEntryPath.packageName.gitRootPath.requiredProjects.dependencies.repositories.superclassName.applicationClassCreationBlock.force..st
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.

It turns out that an encrypted home folder restricts the length of file names. Thus, this was the problem! It seems to work if I install GsDevKit outside my encrypted home folder.

**Comment by dalehenrich** [comment]
Ah, very interesting! I was suspicious that you might have been running on Windows (which has non-encrypted folder filename and path length problems) ... I guess the missing method called ''initializeWithName:superclassName:traitComposition:classTraitComposition:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp:'' could have been a clue :)
