### ISSUE TITLE
CentOS/Redhat - lsb prereq

### ISSUE THREAD

**Issue by petr-fischer** [GsDevKit/GsDevKit_home#177]
When installing on CentOS 7.3, git as prereq is not enough, "redhat-lsb-core" package also needed (lsb_release binary called from install scripts).

**Comment by dalehenrich** [comment]
@petr-fischer do you have an edit to the install scripts? or better yet a pull request with the fix?

**Comment by petr-fischer** [comment]
I have not studied installation scripts yet . I installed it manually. I will look at it.

**Comment by petr-fischer** [comment]
Created pull request #178

**Comment by dalehenrich** [comment]
PR #178 merged ...
