### ISSUE TITLE
filepath too long error during installation

### ISSUE THREAD

**Issue by marcfreiheit** [GsDevKit/GsDevKit_home#185]
I've tried installing GsDevKit_home on my ubuntu machine. During installation step `createStone -f devKit_33 3.3.0` I've run into the appended error. Output of installServerClient looks fine after executing it a second time. 

This class couldn't be installed because it caused a `filepath too long`-error. Unfortunately, I can't reproduce the error and haven’t saved it back then. 
> Error: while installing tODE on server: 'a MessageNotUnderstood occurred (error 2010), a MCClassDefinition does not understand  #''initializeWithName:superclassName:traitComposition:classTraitComposition:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp:'''

fyi: That's the machine we got stuck when you visited us here in Potsdam.

How can I reinstall both server and client in order to reproduce the error?

Outputs (logs, errors, infos):
**Kernel**: 3.13.0-129-generic x86_64
**GS_HOME**: /home/marc/GsDevKit_home
**PATH**: /home/marc/GsDevKit_home/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
[output of lsb_release](https://github.com/GsDevKit/GsDevKit_home/files/1355115/lsb_release.txt)
[output of installServerClient](https://github.com/GsDevKit/GsDevKit_home/files/1355106/installServerClient_output.txt)
[occured error during installation](https://github.com/GsDevKit/GsDevKit_home/files/1355090/gsdevkit_error.txt)

**Comment by dalehenrich** [comment]
Well to try to reproduce this error you can just do a fresh clone of GsDevKit_home in another directory and set GS_HOME to point to new directory ... to cleanup old install use’chmod -R out+w GsDevKit_home’ and then ‘rm’ the directory

**Comment by marcfreiheit** [comment]
I've figured out what's the problem. I cloned your repo into my home directory which is encrypted. Therefore there is a limit of 143 characters per filename. Cloning into another directory worked.

[Bug Description](https://bugs.launchpad.net/ecryptfs/+bug/344878)
