### ISSUE TITLE
installOsPrereqs needs changes for Linux Mint

### ISSUE THREAD

**Issue by HeSe** [GsDevKit/GsDevKit_home#197]
I tried to install Gt4Gemstone client image on Linux Mint.
Part of the installation routine is installing GSDevKit_home prerequisites.

As part of this process installOsPrereqs is executed.
Linux Mint is identified as
osName: Linux
This needs a change here: added " | Linux"
....
case "$osName" in
        Ubuntu | Linux)
		  installPrereqsForUbuntu
		  ;;
        Debian)
....

and osVersion is 18.2
....
    ;;
      14.04|16.04|18.2)
        sudo dpkg --add-architecture i386
        installUbuntuPackages
....

What is weird is that all the prerequisites are already installed and the installation routine still want to install them again...

I haven't the opportunity to fork the project from the machine I am working on right now.
Can I make this changes online, too?

Sebastian

**Comment by dalehenrich** [comment]
You can edit the source from a browser which I think automatically creates a branch and pull request ... I don't think we've tested GemStone on18.2 so if you hit odd problems or errors, keep that in mind ...

**Comment by HeSe** [comment]
Well, 18.2 is not an Ubuntu version.
I think the packages needed for Ubuntu and Mint are the same, though.

So extra entries for "Linux" and "18.2", or add the two to Ubuntu?

**Comment by HeSe** [comment]
fixed with commit 09972e3
