### ISSUE TITLE
typo in cloneGsDevKitProjects?

### ISSUE THREAD

**Issue by victornoel** [GsDevKit/GsDevKit_home#204]
I suppose that if `cloneServer` is true, the server should be cloned, not the client?

Here is a fix:
```
diff --git a/bin/utils/cloneGsDevKitProjects b/bin/utils/cloneGsDevKitProjects
index 04475d6..cca84d2 100755
--- a/bin/utils/cloneGsDevKitProjects
+++ b/bin/utils/cloneGsDevKitProjects
@@ -70,7 +70,7 @@ if [ "$cloneClient" = "true" ] ; then
 fi
 
 if [ "$cloneServer" = "true" ] ; then
-  "$GS_HOME/bin/private/clone_gs_client_dev" $modeArg $organizationArg
+  "$GS_HOME/bin/private/clone_gs_server" $modeArg $organizationArg
 fi
 
 exit_0_banner "...finished"
```

**Comment by dalehenrich** [comment]
I'll have to double check ... but if certainly sounds right:) did you run into a particular problem or is this based on code reading? ... Good catch by the way:)

**Comment by victornoel** [comment]
hehe no, only code reading, because from what I understood, I think that in one way or another, the correct repository will be cloned when it is actually needed.
