### ISSUE TITLE
Seaside 3.5.0 install with tODE and adding packages to a created and loaded project

### ISSUE THREAD

**Issue by ahdach** [GsDevKit/GsDevKit_home#250]
Hi Dale,

I finally toke the time to play around with tODE.
Following the instructions I managed to have Seaside up and running on my (upgraded to High Sierra) laptop.
I had to deviate from the instructions at two occasions.
First, I had to todeLoad the stone before starting the tode client.
And loading Seaside from the menu did not work. I had to load it from the tode comman line (I think the packages dont match, Zinc Project vs Zinc).
I then tried to create a project.

I started with the Foo project in the tutorial.
That worked well until I was trying to add test classes in new package.

Once I have a project loaded, how can I add a new package.
Changing the baseline method of the BaselineOf class seems not enough.
I tried all sorts of project entries but could not achieve this simple task.

Could you please advise.

In the meantime, I'll develop using the following process.

Develop in Pharo 8.
Push to git.
Then test in tODE.

My ultimate goal is to be able to develop in tODE. :)

Thanks
M

**Comment by dalehenrich** [comment]
hi @ahdach, glad to see that you are getting started ... in addition to adding the package to the baseline, you need to co a `mc create <package-name>` in the tODE console (see `man mc`) ... once the package has been created you can create a class in the package by setting the class category of a class (new or old) to the package name ...

**Comment by ahdach** [comment]
It worked.
Thanks
