### ISSUE TITLE
Add flag to set SPC size in upgradeStone command

### ISSUE THREAD

**Issue by pdebruic** [GsDevKit/GsDevKit_home#258]
The default in the system.conf file is 500MB

Remembering to edit the $GEMSTONE/seaside/data/system.conf and $GEMSTONE/seaside/system.conf files to be whatever value you want for the SPC forthe upgrade is a step that the user has to remember that the scripts could handle

The -S flag is unused in the upgradeStone command

**Comment by pdebruic** [comment]
Really I'm not sure where the SPC value needs to be changed.  I can't remember if its the stone that is to be upgrade's system.conf or the system.conf in the to-be-upgraded-to version's product directory

**Comment by dalehenrich** [comment]
I think that I might add this to the createStone command and pass the upgradeStone argument to createStone ... 

Hmmm, would it make sense to clone the system.conf and gem.conf files from the upgraded stone's directory?

**Comment by pdebruic** [comment]
I was thinking more along the lines of just adding the SPC setting from the command line to the conversion.conf file.  Just to maximize upgrade speed. 

But yes copying the system.conf and gem.conf file might help.  

I manually had to set the ICU library [1] for one of the upgrades and the  STN_ALLOW_NFS_EXTENTS [2] setting on another. 

1 - http://forum.world.st/Icu-library-version-mismatch-td5090083.html

2 - http://forum.world.st/Problem-starting-stone-quot-reason-File-is-on-NFS-GEMSTONE-DATADIR-extent0-dbf-quot-td5060764.html

**Comment by dalehenrich** [comment]
Hmmm, this is beginning to sound like it might make sense to allow you to specify a path to your config.conf for the upgrade? Then you can make any and all of the settings that you need in one place?

**Comment by pdebruic** [comment]
I think that makes sense.  But also whatever is easier for you to create and maintain.  I do this so infrequently that stumbling through is OK. 


Also I think the NFS issues is one that's been fixed in GS 3.4x so won't be an issue going forward.

**Comment by pdebruic** [comment]
It looks like the to be upgraded stone's system.conf file is copied.  But because the temp obj cache setting is always set to the default it overrides the setting in the system.conf file.

**Comment by dalehenrich** [comment]
that makes sense, so we probably don't need the SPC settings for upgrade. I'm about to merge the fix for #257 into master, so that the TOC can be set -m and we're probably done?

**Comment by pdebruic** [comment]
yea I think so

**Comment by dalehenrich** [comment]
cool ... thanks for digging a bit deeper into this ... I didn't remember that I had already copied the system.conf files:), but I guess I would have gotten there sooner or later:)

**Comment by dalehenrich** [comment]
#257 merged ...
