### ISSUE TITLE
Ubunti 20.04 Installation failed - not recognized

### ISSUE THREAD

**Issue by feldti** [GsDevKit/GsDevKit_home#290]
There are several points here:
a) The Ubuntu version is not recognized, but this is expectable and can be fixed very fast. In:

~/GsDevKit_home/bin/utils/installOsPrereqs:

      14.04|16.04|18.04|20.04)
        sudo dpkg --add-architecture i386
        installUbuntuPackages
        sudo apt-get -y install fonts-dejavu # ensure that DejaVu Sans Mono font present (default font for tODE)
        sudo ln -f -s /usr/lib/i386-lin-gnu/libstdc++.so.6 /usr/lib/i386-linux-gnu/libstdc++.so
        ;;

and an installServer brings up all downloads and that's it

**Comment by dalehenrich** [comment]
fixed  with this merge commit d050ca6a8
