### ISSUE TITLE
All 22 Seaside/Parasol travis tests consistently failing for GsDevKit_home 

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#299]
[The last time the GsDevKit_home travis tests passed was 23 days ago](https://travis-ci.org/github/GsDevKit/GsDevKit_home/builds/740665986) and it doesn't seem to be a chrome driver problem, but the fact that all of the Parasol tests are all failing is suspicious. 

[The last clean Seaside travis test passed a month ago](https://travis-ci.org/github/SeasideSt/Seaside/builds/734430131).  Implying that Seaside hasn't changed in the last month.

[The last clean GLASS travis test passed 23 days ago](https://travis-ci.org/github/glassdb/glass), implying that GLASS hasn't changed in last 23 days.

[The last clean CRON job for Parasol was 27 days ago](https://travis-ci.org/github/SeasideSt/Parasol/builds/739486502)
so the implication is that Parasol hasn't changed for 27 days.

[The most recent Parasol travis CRON test failed for **all** builds 17 hours ago](https://travis-ci.org/github/SeasideSt/Parasol/jobs/745549689), which implies the changes to cause the failures is not related to GemStone, but is some sort of deeper issue with Parasol...

**Comment by jbrichau** [comment]
@dalehenrich 
From the logs of the Parasol builds, I can see that the Chrome version changed and we did not update the chromedriver accordingly. I now updated the chromedriver version and I suspect all will run well again.

Now I'm just waiting for Travis-CI to even start a build... I will be looking at alternatives.

**Comment by dalehenrich** [comment]
Excellent! I'll update the chrome version in GsDevKit_home as well ... Thanks ...

If/when you find a travis alternative, let me know :)

**Comment by jbrichau** [comment]
> If/when you find a travis alternative, let me know :)
I'm giving Github actions a try with the Smalltalk-CI action. Seems like it errors for Gemstone. Did you ever try it?

**Comment by dalehenrich** [comment]
I have not tried it ... and I have not read about it, so I'm not even sure what it does ...

**Comment by jbrichau** [comment]
@dalehenrich you can take a peek here: https://github.com/SeasideSt/Seaside/runs/1495474848
Seems like I'm running into an issue that the prerequisites for gsdevkit are not installed. 

(in the meantime, after several hours, the Seaside build on Travis-CI has run 4 jobs and the Parasol builds did not even start yet... sigh)

**Comment by dalehenrich** [comment]
Yeah it looks like you right ... at the moment it is not as simple as unpacking a GemStone version and running code, since native GemStone doesn't know anything about packages ... when we ship Rowan with the product, we should be able to greatly simplify the SmalltalkCi process to behave much more like Pharo and Squeak ... if this is a SmalltalkCi feature, it is theoretically possible to get it working with GsDevKit_home ...

**Comment by jbrichau** [comment]
@dalehenrich https://github.com/SeasideSt/Seaside/runs/1503440413
Builds are green again for Seaside (once I merge that PR) and now also available via github actions instead of travis-ci.

**Comment by dalehenrich** [comment]
Cool that the github actions are working for GemStone ... are you still running on travis or have you abandoned travis altogether?

**Comment by dalehenrich** [comment]
looking at the github action... I don't see where you install the chrome-driver? Is the chrome-driver code part of a stable install? And I don't see where you start the selenium job ...

**Comment by dalehenrich** [comment]
Okay , I see that the `start` is part of the install for selenium, so I guess the chrome drive must magically appear ... or does that imply that downloading a chrome-driver isn't necessary? and I just need to launch selenium?

I don't have the time to convert GsDevKit_home to use github actions, but I do have time to wait for travis jobs:) ... for now I'll stick with the old way ... until I find the time ... but I think that github actions looks like the way to go ...

**Comment by jbrichau** [comment]
I’m still running Travis as well. The entire selenium universe, including matching chromedriver for the installed Chrome is installed via a npm package I found (see build). So, that is a bonus as well.

**Comment by dalehenrich** [comment]
@jbrichau, aha! That'll be perfect for travis runs ... we run internal builds on multiple hosts with varying versions of Chrome, so I will have to take that into account the next time I update the GsDevKit_home seaside build scripts ...

Thanks a ton for the info!

**Comment by dalehenrich** [comment]
okay ... the _home builds are running clean ... mission accomplished ... looks like the Grease runs are clean as well !
