### ISSUE TITLE
make finding installlation steps easier

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#38]
as a corollary to this I'd once i hit the installation page, I'd like a "prominent link" to the sample script (or the sample script is at top with explanation to follow?)  ... 

My rationale is that for some of these steps I want to use the example script multiple times after I've read the detailed documentation ... so knowing that it exists and finding are two different things:)

**Comment by LisaAlmarode** [comment]
fixed in pull request LisaAlmarode#9
