### ISSUE TITLE
How to handle osprereqs for non-Ubuntu linux platforms

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#41]
For windows the only prerequisite is to install [GitHub for Windows](https://github.com/GsDevKit/GsDevKit_home/blob/master/docs/installation/README.md#installation_on_separate_server_and_client) which includes a bash shell.

For mac one must install XCode from the app store (to get git) and then the installOsPrereqs script configures the system for shared memory.

For Ubuntu, there is a laundry list of packages that need to be installed and `apt-get` does the job ...

Other non-Ubuntu Linux systems have package managers similar to `apt-get` and we need to automate each one as well as make it straightforward for:
- allowing manual installation on new platforms
- adding custom installation scripts for different platforms

**Comment by dalehenrich** [comment]
@marianopeck, I've "assigned this to you" because I'd like to understand the os prereq installtaion process that you use for CentOs(?). On the dev branch I've restructured the installation to automatically call the installOsPrereqs script, but I currently only have support for Ubunutu 12.04/14.04, Windows, and Mac ... I'd like to somehow generalize this to allow for adding support new Linux distributions and You are my first guinea pig:)

**Comment by marianopeck** [comment]
Dale, quick question....  one thing is the pre-request to have gsDevKit_home installed (git, etc), and another thing is to be able to run Pharo in order to do X11. Which one do you want? If we consider tODE as part of gsDevKit_home I would guess both.  If true, would you like all those pre-reques separated (in gsDevKit vs Pharo) or all together?

**Comment by marianopeck** [comment]
Dale, I still have doubts about this. For example, if you install the client in CentOS too, you may need to run Pharo (to do todeIt for example) yet you don't want to do X11 forward?   In other words, should I assume that X is installed as part of the pre-reques? because there are different flavors of CentOS (as most Linux) so I don't know which one should be considered.

**Comment by dalehenrich** [comment]
Yeah the 32-bit X11 stuff is there because defKitCommandLine does run on the server whether or not you are actually using a tODE client ... it runs headless, but if there is an issue with some of the headless pharo operations, I want to be able to tell the user to use the -D flag to bring up a pharo debugger on an error and for that I need to have the option to run pharo in headful mode.

I am taking the approach that if you don't like the way that the prereqs are installed, then you are free to install the prereqs that you want and `touch $GS_HOME/bin/.osPrereqsSysSetup` to skip the GsDevKit_home prereq installation ...

Naive users may skip the manual install prereqs step altogether and then get in deeper trouble down the road ... so I've decided to give folks who care about how prereqs are installed a way to take control themselves...

**Comment by dalehenrich** [comment]
The 32-bit x11 client libs are the bare minimum that needs to be installed to be able to do x11 forwarding or to run on a full x11 desktop ... so it's is truly up to the user whether or not they have a full x11 desktop on there server, but as I said, by default i will install the 32-bit x11 client libs so that the user is free to change her mind about how the client will be handled ()x11 forwarding or netldi  port forwarding) without complicating things on the prereqs end ...

As a general principle I expect that serious production users will end up customizing things or even building there own deployment scripts ... but I want the GsDevKit_home environment to get folks to the point where they have time to develop their app and even take it into production without having to take a deep dive on devop issues ...

**Comment by dalehenrich** [comment]
The script is passing tests on both osx and linux .... need to test Centos .... @marianopeck be aware that I've changed the arguments to the install* scripts to where no args are required (Issue #33) it also means that you have to run an explicit createStone and/or createClient instead of getting one created for **free** during install ... other than that I've been mostly reworking the internals ...

**Comment by dalehenrich** [comment]
@marianopeck when you've tested the new script on Centos, go ahead and mark this issue cloased ...

**Comment by marianopeck** [comment]
OK. When I tried centOS I tried mostly each instruction separately. I think that the best thing would be that I get again a fresh CentOS, I clone gsDevKit_home, checkout dev and then try installServerClient, createStone, createClient, etc. And everything should work automatically out of the box. 
Correct?

**Comment by dalehenrich** [comment]
That's the hope:) Also don't forget to use the dev branch:) .. The following should be a sufficient smoke test:

```
installServerClient -o GsDevKit
createStone gs_3211 3.2.11
createClient tode 
status
stopStone -b ${STONENAME1}
```

I guess I'd like to know if the following works on CentOS:

```
installServerClient -o GsDevKit |& tee $GS_HOME/install.log
createStone gs_3211 3.2.11 |& tee -a $GS_HOME/install.log
createClient tode  |& tee -a $GS_HOME/install.log
status  |& tee $GS_HOME/install.log
stopStone -b gs_3211  |& tee $GS_HOME/install.log
```

That should create a complete log of everything in $GS_HOME/install.log, while also dumpoing things to stdout for progress and immediate feedback upon errors ...

**Comment by marianopeck** [comment]
mmm I am getting a problem trying to create the stone. It seems it cannot download anymore gemstone zip. It shows:

	Downloading GemStone/S 3.2.10
	[Info] Starting download of GemStone64Bit3.2.10-x86_64.Linux on localhost.localdomain
	[Info] Downloading GemStone64Bit3.2.10-x86_64.Linux.zip using /usr/bin/wget --no-verbose

And hangs there...

**Comment by marianopeck** [comment]
BTW, in `downloadGemStone` from dev branch, I would change this line `echo "[Info] Downloading $gss_file using ${cmd}"`  to  `echo "[Info] Downloading ${ftp_address}/pub/GemStone64/$bucket/$gss_file using ${cmd}"`
 
That way I can copy paste in command line and see if I can reproduce the problem.

**Comment by dalehenrich** [comment]
okay good to know ... I must have messed up the args to wget  when I added the --no-verbose .... I'll take a look and I should have a new check-in in a minute or two ...

**Comment by dalehenrich** [comment]
Could you check the man page for wget on CentOS? The following works for me:

```
wget --no-verbose ftp://ftp.gemtalksystems.com/pub/GemStone64/3.2.11/GemStone64Bit3.2.11-x86_64.Linux.zip
```

Now there is no progress bar being displayed, but that is what --no-verbose does for you ...

**Comment by dalehenrich** [comment]
Okay I've pushed a new version of downloadGemStone with the new feedback you've requested

**Comment by dalehenrich** [comment]
... headed home ... I'll checkj on-line when I get a chance...

**Comment by marianopeck** [comment]
Thanks. I am trying again and doing a `ls` over the zip file and it seems the zip is being download...it's just taking a life...but moving... OK, I thought it hung because I was used to see the progress bad and now I see the --no-verbose. I guess this last change was on purpose for the install.log?

**Comment by marianopeck** [comment]
OK...Dale, I still need to fix a couple of things for CentOS. Will let you know tomorrow and do a pull request. Please do not make this public/ann yet.

**Comment by marianopeck** [comment]
No..actually, I think it was your fault ;)    You set `x11client="true";;`   but then you test via `"${X11client}x" = "1x"` and so it's always false.

**Comment by marianopeck** [comment]
OK, btw the `tee` to the `install.log` does work. But be careful because in the instructions you pasted by above, you forgot some `-a` and that would override the file ;)

**Comment by marianopeck** [comment]
OK, I have everything working now. I will try to make a commit later today.

**Comment by marianopeck** [comment]
OK Dale I made this pull #42 which fixes the remaining issues. Note that I made the pull request over `dev` branch rather than `master` since my work started from `dev` branch. But I am not sure if the pull request should have been done for `dev` as I did or for `master`. Please let me know which should have been the correct path. Thanks and enjoy Thanksgiving.

**Comment by dalehenrich** [comment]
Woops .... good catch ... I've merged the ?PR
