### ISSUE TITLE
docs/installation/configOSForSingleNode.md comments

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#44]
from @martinmcclure)

In GsDevKit_home/docs/installation/configOSForSingleNode.md, it should specify that the "Linux" instructions are for Ubuntu, and which Ubuntu version it's for (14.04, I'd guess, but I don't know?). Package names and commands vary by distro. Over time we'll probably provide instructions for more distros, or provide a repo that has the appropriate prereqs.

**Comment by LisaAlmarode** [comment]
I have created a new file configureOS.md, and plan to delete the three other configureOS* .mds.
configureOS.md distinguishes Ubuntu and Centos, but not version.  Unless there any known cases of differences between versions, I'd rather omit version... the install is a very minimal set now.

**Comment by dalehenrich** [comment]
sounds good integrated PR #64 and will leave this bug open as a reminder to delete the files ...

**Comment by LisaAlmarode** [comment]
Files were deleted on February 11, closing
