### ISSUE TITLE
docs/installation/installDevKitServerAndClient.md comments

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#45]
In
GsDevKit_home/docs/installation/installDevKitServerAndClient.md

section 3. Set the environment says

 "export GS_HOME=<githubdirectory>"

This is incorrect. I assume it should say

 "export GS_HOME=<githubdirectory>/GsDevKit_home"

**Comment by LisaAlmarode** [comment]
There was a angle-bracketed pathname after the equal sign.  While it looks okay to me on github, seems to not be visible in all cases. Real fix is to stop using angle brackets for variables.

**Comment by LisaAlmarode** [comment]
Estaban fixed this earlier, and merged in my branch.
