### ISSUE TITLE
installServer appends kernelm* settings to sysctl.conf even if they're already there

### ISSUE THREAD

**Issue by martinmcclure** [GsDevKit/GsDevKit_home#46]
...also, now that I look, there are no such files as /proc/sys/kernelmmax or /proc/sys/kernelmall, so I don't think these entries in sysctl.conf are doing anything at all.

What are they supposed to do?

**Comment by dalehenrich** [comment]
Well... that is pretty ancient code written by Monty 6-7 years ago ... It looks the script [is trying to avoid multiple entries](https://github.com/GsDevKit/GsDevKit_home/blob/dev/bin/utils/installOsPrereqs#L250), but I suppose `grep -sc "kern.*m" /etc/sysctl.conf` is not actually matching `kernelm*` ...

I'm going to guess that the `/proc/sys/kernelm*` entry changes the setting in the current system and the entry in sysctl.conf ensures that those values are set upon reboot ... The scripts do appear to successfully update the shared memory settings, so something is working there:)

**Comment by martinmcclure** [comment]
The script is indeed trying to avoid multiple entries. It fails and adds the multiple entries because /etc/sysctl.conf is not readable by non-root users on my system. This grep should probably be done with sudo. The script *does* use sudo to *modify* /etc/sysctl.conf.

But if it does that it will fail to add the entries. This is because the grep matches too much. On my system, I see this:

> mite etc # grep -s "kern.*m" /etc/sysctl.conf
> kernel.shmmax = 0x100000000
> # When the kernel panics, automatically reboot in 3 seconds
> #kernel.pid_max = 999999
> # kernelm* settings added by GsDevKit installation
> kernelmmax=4294967296
> kernelmall=18446744073692774399
> # kernelm* settings added by GsDevKit installation
> kernelmmax=4294967296
> kernelmall=18446744073692774399

As you can see, it's matching things that have nothing to do with shared memory, including some comments. A better grep would be for 

> "^kernel\.shm"

Looking at it more closely, I think the entire stanza from lines 248 to 278 should be removed. Persistent setting of shmmax is being done by line 234, and a similar line should be added after line 243 for shmall. At least for Linux, I'm not sure about Darwin's settings. Perhaps the Darwin parts of that stanza are still needed.

**Comment by dalehenrich** [comment]
thx ... (a pull request would help -- haha) ... travis tests are actually run against both linux and osx machines, so the PR test would expose aany linux/mac issues ...

**Comment by dalehenrich** [comment]
Good point ... I'll add `&& sudo /bin/su -c "echo 'kernel.shmall=$shmallNew' >>/etc/sysctl.conf"` for setting small on linux, I'll leave things alone for Mac ...
