### ISSUE TITLE
document setting hostname ... 

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#53]
add `<host-name>` to `/etc/hosts`and:
- linux: 

  `sudo hostname <host-name>`
  `sudo vi /etc/hostname ` and change to <host-name>

- osx: ` sudo scutil --set <host-name`

**Comment by dalehenrich** [comment]
I think that we need to change the document and use `sudo hostname` for mac and linux ... I think that `scutil` changes the wrong hostname ... don't ask:)

**Comment by LisaAlmarode** [comment]
Fixed in commit https://github.com/LisaAlmarode/GsDevKit_home/commit/c8436d5f4f4f95b6154bd12386cf1f0b5cf8e6f8
