### ISSUE TITLE
installClient installs a server & installServer attempts to install a client

### ISSUE THREAD

**Issue by pdebruic** [GsDevKit/GsDevKit_home#65]
Is there a way to get just a server installed on a remote server, and just a client installed on my laptop?

I don't want to add the 32 bit libs for pharo on the remote system, just to be able to install GS.  Thanks

**Comment by pdebruic** [comment]
oh sorry.  misspoke.  It installs Pharo and attempts to use it in the server creation process.

**Comment by dalehenrich** [comment]
right ... I do all of the algorithmic heavy lifting in Pharo ... I wasn't about to do that work in bash, I didn't want to have to learn ruby when I already know smalltalk:)
