### ISSUE TITLE
upgradeStone gives a aGsMethodDictionary in objectSecurityPolicyId 1 with insufficient authorization

### ISSUE THREAD

**Issue by pdebruic** [GsDevKit/GsDevKit_home#67]
when running the upgradeSeasideImage script upgrading from a 3.2.4 to either 3.2.12 or 3.3.0 stone.

I can email you the log file if you like.  

Is that a permission error I need to fix in the stone I'm upgrading?

**Comment by pdebruic** [comment]
Its trying to remove all the methods from the Duration class. So I've excluded that one and am running it again.

**Comment by pdebruic** [comment]
hmm so its past the objectSecurityPolicy id error and now seems to stop after it unloads GsFailedMethodCompilationDuringCopyMethodToNewClass and then sends it #removeFromSystem

definition unloaded: 'aMCMethodDefinition(GsFailedMethodCompilationDuringCopyMethodToNewClass>>signal:with:)'
definition unloaded: 'aMCMethodDefinition(GsFailedMethodCompilationDuringCopyMethodToNewClass>>failedMethodCompilations)'
definition unloaded: 'aMCMethodDefinition(GsFailedMethodCompilationDuringCopyMethodToNewClass>>defaultAction)'
definition unloaded: 'aMCMethodDefinition(GsFailedMethodCompilationDuringCopyMethodToNewClass class>>signal:with:)'
definition unloaded: 'aMCClassDefinition(GsFailedMethodCompilationDuringCopyMethodToNewClass)'
-----------------------------------------------------
GemStone: Error         Nonfatal
a MessageNotUnderstood occurred (error 2010), a GsFailedMethodCompilationDuringCopyMethodToNewClass class does not understand  #'removeFromSystem'
Error Category: 231169 [GemStone] Number: 2010  Arg Count: 4 Context : 2875623425 exception : 2875752705
Arg 1: [33168129 sz:16 cls: 110849 Symbol] removeFromSystem
Arg 2: [2 sz:0 cls: 74241 SmallInteger] 0 == 0x0
Arg 3: [2509327361 sz:19 cls: 2509341953 GsFailedMethodCompilationDuringCopyMethodToNewClass class] GsFailedMethodCompilationDuringCopyMethodToNewClass
Arg 4: [2876051969 sz:0 cls: 66817 Array] anArray

**Comment by pdebruic** [comment]
moving the patch for #removeFromSystem above the install of the base GLASS libraries in the bootstrapSeasideImage.topaz script avoids the bug in the preceding comment.

**Comment by dalehenrich** [comment]
I would like to see the log file ... I've been testing a number of 
different upgrade, paths, so this will be interesting to see if there's 
something there ... also interested in see the project list from your 
3.2.4 (print window)...

Are you using the most recent GsDevKit_home release?

**Comment by dalehenrich** [comment]
This is very strange ... btw how did you "exclude that one"

**Comment by dalehenrich** [comment]
@pdebruic the upgrade steps should not be removing any classes ... especially these classes ...

You don't happen to be using Bootstrap ... there is a known package conflict with the Bootstrap code - GemStone has had a Bootstrap package since the very beginning and if you are using Bootstrap, then that explains why these classes are being removed ...

The only solution is to rename the newer Bootstrap package before upgrade ...

**Comment by pdebruic** [comment]
Yes its the most recent GsDevKit_home release. 

I think the Duration and DateAndTime classes were affected because I'm using Chronos in my app.  It installs itself in UserGlobals as the DateAndTime and Duration class when installed.  But I had to remove it to do the upgrade because the upgrade scripts install some methods with a temp var named 'year' which exists in the class the method is being installed in.  To exclude it I just changed the bootstrapSeasideImage code to test for the class name and not remove the methods when matching e.g.

```
! remove all of the methods from all of the classes in BootstrapSymbolDictionaryName
run
BootstrapSymbolDictionary values doWithIndex: [:global :index |

    (global isBehavior and:[(#('Duration' 'DateAndTime') includes: global asString )not])
        ifTrue: [
            global removeAllMethods.
            global class removeAllMethods ]].
true
%
commit 
```

I'm not using Bootstrap.  If I wasn't using Chronos I don't think I'd have any of these problems.

**Comment by pdebruic** [comment]
Oh and the upgrade finished after move the #removeFromSystem patch up in the bootstrapSeasideImage.topaz file

**Comment by dalehenrich** [comment]
Okay ... I haven't looked at the Chronos package (loation and load 
instructions?), but I'm still not sure why the system is  trying to 
remove those classes without some sort of package operation ... the 
removeFromSystem patch means that none of the classes that _should_ be 
removed will get removed either ... which may or may not show up as a 
problem later ...

Once I get my hands on the Chronos package, I will understand more and 
perhaps be be able to figure out a clean upgrade path ...

Dale

**Comment by pdebruic** [comment]
Oh OK.  Its here: http://smalltalkhub.com/#!/~Chronos/Chronos


MCHttpRepository
	location: 'http://smalltalkhub.com/mc/Chronos/Chronos/main'
	user: ''
	password: ''

**Comment by pdebruic** [comment]
Also - I'm planning to dump the Chronos package so only look into this if it helps you with your upgrade process testing
