### ISSUE TITLE
wrong version used in example

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/GsDevKit_home#82]
[doru was following an example and had the download fail](http://forum.world.st/tode-st-problems-with-downloadGemStone-on-Mac-tp4885396.html), because the version number used was `3.3` instead of `3.3.0` ... I'll fix that one and any other obvious places ... presumably there could be a bunch of places where the version number was incorrectly updated

**Comment by dalehenrich** [comment]
@LisaAlmarode I may have caught the only place where this change was made with 71bb979 ... there might be more in your dev branch ... once you've cleaned up, I will want to think about the download script and possibly allow for 3.3 as a version number arg - this won't be easy, because the version number is used as an `index` into the product downloads and we don't name our downloads with only major and minor version numbers ... but I want to think about it anyway ...

**Comment by dalehenrich** [comment]
20d7c7c should have gotten all of the changes that were made in your last merge ...

**Comment by LisaAlmarode** [comment]
Fixed in pull request https://github.com/GsDevKit/GsDevKit_home/pull/84
versions 3.3 changed to 3.3.0, Dale has agreed that devKit_33 is not unacceptable.
