### ISSUE TITLE
FileWriteError executing `createStone` on a fresh GsDevKit client-server install on Mac OS X

### ISSUE THREAD

**Issue by jbrichau** [GsDevKit/GsDevKit_home#90]
I just followed the installation instructions for setting up a client-server install on my Mac. When executing `createStone`, the script fails with a FileWriteError (see attached log).

I have write access to the file and my disk has plenty of space left. Not sure where to look and debug to find the origin of this error, so I'm reporting it here.

[createstone-filewriteerror-log.txt](https://github.com/GsDevKit/GsDevKit_home/files/191472/createstone-filewriteerror-log.txt)

**Comment by jbrichau** [comment]
It seems I was wrong regarding the file permissions. The `gsDevKitTmp.changes` and `gsDevKitTmp.image` files have a permission setting of 644. Setting it to 655 (at least) resolves the issue.

I followed standard install instructions. I this only an issue for me?

**Comment by dalehenrich** [comment]
Interesting ... I run GsDevKit_home builds on travis OSX all of the time and while it does [succeed occationally --- and recently[(https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/118139140#L1420-L1459) ... I do recall seeing randomw FileWrite errors and wrote them off as travis odditities ...

Now that it's happened in the "real world" I would like to figure things out ... perhaps we could try to figure it out, or perhaps we should change permissions unconditionally? 

If you could share your patch as a PR (on the master branch would be fine) I don't think there will be any harm ... I'm just surprised that pharo would randomly have trouble with a) creating the files of the wrong permissions or b) not being able to overwrite a file that was created 30 seconds ago by the same user ---- randomly...

**Comment by jbrichau** [comment]
Oh, the only thing I did was manually changing the file permissions on the `gsDevKitTmp.changes` and `gsDevKitTmp.image` files. After that, the createStone step worked well and I could continue the instructions. The funny thing is, that when I look now, the created `gsDevKitCommandLine.changes` has the same 644 permissions and I have no issue whatsoever.

**Comment by dalehenrich** [comment]
Okay ... like I said, I've seen this randomly with the mac but never 
experienced it myself --- I build stones, but don't do it regularly ...

I will see if I can figure out a way to fix this - when I get a chance 
... let me know if you have additional troubles and I'll bump the 
priority...

Dale

**Comment by jbrichau** [comment]
I just ran through a complete new setup and experience no issue.
I did this yesterday as well, up to 2 times and got the error I mentioned on both occassions.

Closing this issue. If it pops up again for me or others, we can investigate further.
Thanks for the feedback.

**Comment by jvalteren** [comment]
I am running into the same issue. Have repeatedly tried to create a stone (v3.4.3) on Mac OS X, with the same error. After trying Johan's suggestion to change permissions to 655, the (re-)install worked.

After the install, I see that the permissions of the `GsDevKit_home/shared/pharo/gsDevKitTmp.changes` file are back to 644. However, the file `gsDevKitTmp.image` has retained the 655 permissions.

Let me know if you're interested in the command line output.
