### ISSUE TITLE
Client install on Windows broken for 3.3

### ISSUE THREAD

**Issue by LisaAlmarode** [GsDevKit/GsDevKit_home#92]
GS64 renamed the windows client from GemBuilderC to WindowsClient in v3.3.

**Comment by dalehenrich** [comment]
@LisaAlmarode so you reverted the changes for this issue (35bcaa2 and 23dad4a) ... does that mean that this issue is not fixed?

**Comment by dalehenrich** [comment]
I see that we still have the fix that matters....in bin/private/installGci b5c722e40a4614587449f5330027a1a61e17f572

**Comment by LisaAlmarode** [comment]
Two fixes required, bin/downloadGemStone and bin/private/installGci; two reverts were backing out duplicate fixes.
