### ISSUE TITLE
Install should return a short final status line

### ISSUE THREAD

**Issue by LisaAlmarode** [GsDevKit/GsDevKit_home#95]
Since the output is so verbose, it is not easy to see that an error occurred, until something doesn't work and you eventually check the log.

As the final line of Install output, there should be a single line status indicating success or failure.

**Comment by dalehenrich** [comment]
Also improve the error messages ... installServer, deleteClient, createClient are exemplars

**Comment by dalehenrich** [comment]
While touching all script files, update copyright notice to reference MIT license

**Comment by dalehenrich** [comment]
Still work to be done updating the secondary scripts
